apiVersion: apps/v1
kind: Deployment
metadata:
  name: icsquiz-user-app
spec:
  selector:
    matchLabels:
      app: icsquiz-user-app
  template:
    metadata:
      labels:
        app: icsquiz-user-app
    spec:
      containers:
        - name: icsquiz-user-app
          image: icsquiz-user-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3090

          envFrom:
            - configMapRef:
                name: global-config

          env:
            - name: SERVER_PORT
              value: "3090"

          # ðŸš€ Added required CPU & Memory requests/limits for HPA to work
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: icsquiz-user-service
spec:
  selector:
    app: icsquiz-user-app
  type: NodePort
  ports:
    - port: 3090
      targetPort: 3090
      nodePort: 30090   # must be between 30000â€“32767
