apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icsquiz-backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: icsquizuserservice.deepseahost.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: icsquiz-user-service
                port:
                  number: 3090
